spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      format_sql: true

  sql:
    init:
      mode: always
      platform: h2

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080
